import React from "react";

const PrivacyPolicy: React.FC = () => {


  return (


    <div className="bg-gradient-warm min-h-screen w-full flex justify-center">


      <div className="max-w-7xl w-ful p-6 leading-relaxed text-gray-800">


        <h1 className="text-3xl font-bold mb-6 text-center">Privacy Policy</h1>
        <p className="text-center"><strong>Last updated:</strong> August 29, 2025</p>
        <p className="mt-4 text-center">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="mt-2 text-center">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-6">Interpretation and Definitions</h2>
        <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-xl font-semibold mt-4">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-disc ml-6 mt-2 space-y-2">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Rums Enterprise, Pullikadavu Road, Perumugham, Feroke, Kozhikode, Kerala 673631.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Kerala, India</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company...</li>
          <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website...</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service...</li>
          <li><strong>Website</strong> refers to sajbiopak.com, accessible from <a href="https://sajbiopak.com" className="text-blue-600 underline">https://sajbiopak.com/</a></li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company...</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6">Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-semibold mt-4">Types of Data Collected</h3>
        <h4 className="text-lg font-semibold mt-3">Personal Data</h4>
        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information...</p>
        <ul className="list-disc ml-6 mt-2 space-y-1">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h3 className="text-xl font-semibold mt-4">Usage Data</h3>
        <p>Usage Data is collected automatically when using the Service...</p>

        <h3 className="text-xl font-semibold mt-4">Information from Third-Party Social Media Services</h3>
        <ul className="list-disc ml-6 mt-2 space-y-1">
          <li>Google</li>
          <li>Facebook</li>
          <li>Instagram</li>
          <li>Twitter</li>
          <li>LinkedIn</li>
        </ul>
        <p className="mt-2">If You decide to register through or otherwise grant us access...</p>

        <h3 className="text-xl font-semibold mt-4">Tracking Technologies and Cookies</h3>
        <p>We use Cookies and similar tracking technologies to track the activity...</p>
        <ul className="list-disc ml-6 mt-2 space-y-1">
          <li><strong>Cookies or Browser Cookies</strong>...</li>
          <li><strong>Web Beacons</strong>...</li>
        </ul>
        <p className="mt-2">Cookies can be "Persistent" or "Session" Cookies...</p>

        <h2 className="text-2xl font-semibold mt-6">Use of Your Personal Data</h2>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc ml-6 mt-2 space-y-1">
          <li>To provide and maintain our Service...</li>
          <li>To manage Your Account...</li>
          <li>For the performance of a contract...</li>
          <li>To contact You...</li>
          <li>To provide You with news, special offers...</li>
          <li>To manage Your requests...</li>
          <li>For business transfers...</li>
          <li>For other purposes...</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6">Retention of Your Personal Data</h2>
        <p>The Company will retain Your Personal Data only for as long as is necessary...</p>

        <h2 className="text-2xl font-semibold mt-6">Transfer of Your Personal Data</h2>
        <p>Your information, including Personal Data, is processed at the Company's operating offices...</p>

        <h2 className="text-2xl font-semibold mt-6">Delete Your Personal Data</h2>
        <p>You have the right to delete or request that We assist in deleting the Personal Data...</p>

        <h2 className="text-2xl font-semibold mt-6">Disclosure of Your Personal Data</h2>
        <p><strong>Business Transactions:</strong> If the Company is involved in a merger...</p>
        <p><strong>Law enforcement:</strong> Under certain circumstances...</p>
        <p><strong>Other legal requirements:</strong> The Company may disclose Your Personal Data...</p>

        <h2 className="text-2xl font-semibold mt-6">Security of Your Personal Data</h2>
        <p>The security of Your Personal Data is important to Us...</p>

        <h2 className="text-2xl font-semibold mt-6">Children's Privacy</h2>
        <p>Our Service does not address anyone under the age of 13...</p>

        <h2 className="text-2xl font-semibold mt-6">Links to Other Websites</h2>
        <p>Our Service may contain links to other websites...</p>

        <h2 className="text-2xl font-semibold mt-6">Changes to this Privacy Policy</h2>
        <p>We may update Our Privacy Policy from time to time...</p>

        <h2 className="text-2xl font-semibold mt-6">Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc ml-6 mt-2">
          <li>By email: sajbiopak@gmail.com</li>
        </ul>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
